## Course Assignment Instructions
You should have Python (version 3.8 or later) and Jupyter Notebook installed to complete this assignment. You will write code in the empty cell/cells below the problem. While most of this will be a programming assignment, some questions will ask you to "write a few sentences" in markdown cells. 

Submission Instructions:

Create a labs directory in your personal class repository (e.g., located in your home directory)
Clone the class repository
Copy this Jupyter notebook file (.ipynb) into your repo/labs directory
Make your edits, commit changes, and push to your repository
All submissions must be pushed before the due date to avoid late penalties

* Install the numpy, scipy, statsmodels, and pandas packages (we will be using these throughout the semester)

In [12]:
pip install numpy scipy statsmodels pandas

Note: you may need to restart the kernel to use updated packages.


* Print out the numerical constant pi with ten digits after the decimal point using constant 'pi'. You will need to use the math module in python for this. 

In [14]:
import math

print(math.pi)
print(round(math.pi,10))

3.141592653589793
3.1415926536


* Sum up the first 103 terms of the series 1 + 1/2 + 1/4 + 1/8 + ... use base python

In [16]:
sum(1/(2**i) for i in range (103)) 

2.0

using numpy

In [18]:
import numpy as np

total = sum(1/(2**i) for i in range (103)) 
print(total)

2.0


 * The issue here arises because NumPy's 2 ** np.arange(103) may overflow for very large exponents, leading to incorrect results. NumPy uses fixed-precision data types, which can cause problems when dealing with extremely large numbers.  * The issue here arises because NumPy's 2 ** np.arange(103) may overflow for very large exponents, leading to incorrect results. NumPy uses fixed-precision data types, which can cause problems when dealing with extremely large numbers.

In [20]:
import numpy as np

total = sum(1/(2**i) for i in range (103)) 
print(total)

2.0


* Find the product of the first 387 terms of `1 * 1/2 * 1/4 * 1/8 *` ...

using base python

In [23]:
bar = 1
for i in range(387):
    bar *= 1/2**i
print(bar)

0.0


using numpy

In [25]:
num = np.prod(1/(2.0**np.arange(387)))
print(num)

0.0


Is this answer *exactly* correct?

No, this answer is not exactly correct. The number should be positive although very small and the answer generated is a result of numerical underflow.

* Figure out a means to express the answer more exactly. Not compute exactly, but express more exactly.

In [28]:
import math as m

num = -m.log(2)*sum(range(387))
print(num)

-51771.856063202875


* using numpy ... Hint: use the `log` and `sum` functions in numpy

In [30]:
-np.log(2) * np.sum(np.arange(387))

-51771.856063202875

* Create the sequence `x = [Inf, 20, 18, ..., -20]`.

Pure python

In [33]:
# Create the sequence
x = [float('inf')] + list(range(20, -21, -2))

# Print the result
print(x)

[inf, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0, -2, -4, -6, -8, -10, -12, -14, -16, -18, -20]


Using numpy

In [35]:
# Create the sequence
x = [float('inf')] + list(np.arange(20, -22, -2))

# Print the result
print(x)

[inf, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0, -2, -4, -6, -8, -10, -12, -14, -16, -18, -20]


*   Create the sequence `x = [log_3(Inf), log_3(100), log_3(98), ... log_3(-20)]` ... Use `log` from numpy.

In [37]:
import numpy as np 

x = [float('inf')] + list(np.log(np.arange(100, 0, -2)) / np.log(3))

print(x)

[inf, 4.19180654857877, 4.173417251894302, 4.154648767857287, 4.135485128951194, 4.115909337343186, 4.095903274289384, 4.07544759935851, 4.0545216380691365, 4.0331032563043365, 4.011168719591413, 3.9886925350037563, 3.9656472730442496, 3.9420033663892897, 3.9177288817897304, 3.892789260714372, 3.8671470234508067, 3.8407614303054807, 3.813588092215595, 3.785578521428744, 3.756679610828472, 3.7268330278608417, 3.6959745056821194, 3.6640330098757947, 3.6309297535714573, 3.5965770266157073, 3.5608767950073115, 3.5237190142858297, 3.4849795837717283, 3.4445178457870527, 3.4021735027328797, 3.357762781432299, 3.3110736128178324, 3.2618595071429146, 3.2098316767340234, 3.154648767857287, 3.0959032742893844, 3.033103256304337, 2.96564727304425, 2.8927892607143724, 2.8135880922155954, 2.7268330278608417, 2.630929753571457, 2.5237190142858297, 2.402173502732879, 2.2618595071429146, 2.095903274289385, 1.892789260714372, 1.6309297535714573, 1.2618595071429148, 0.6309297535714574]


* Create a vector of booleans where the entry is true if `x[i]` is positive and finite. Use `&` from base python along with `isnan` and `isinfinite` from numpy

In [39]:
x = np.array(x)
y = ~np.isnan(x) & np.isfinite(x) & (x > 0)

print(y)

[False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]


* Locate the indices of the non-real numbers in this vector. Numpy has a `where` function in lieu of R's `which`

In [41]:
np.where(y == False)

(array([0], dtype=int64),)

* Locate the indices of the infinite quantities in this vector using `where` and `isinf` from numpy.

In [43]:
inf_reals = np.where(np.isinf(x))

print(inf_reals)

(array([0], dtype=int64),)


* Locate the indices of the min and max in this vector. Hint: use the `arg.min` and `arg.max` functions from numpy

In [45]:
x_min = np.argmin(x)
x_max = np.argmax(x)

print(x_min, x_max)

50 0


* Count the number of unique values in `x`. Use `unique` from numpy.

In [47]:
len(np.unique(x))

51

* Cast `x` to a factor. Do the number of levels make sense? Should be 53 unique values. Use `categorical` from pandas.

In [49]:
import pandas as pd

# Cast x to a categorical (similar to as.factor(x) in R)
x_factor = pd.Categorical(x)

# Check the unique levels (categories)
levels = x_factor.categories
num_levels = len(levels)

print(f"Factor levels: {levels}")
print(f"Number of levels: {num_levels}")

#51 levels?

Factor levels: Index([0.6309297535714574, 1.2618595071429148, 1.6309297535714573,
        1.892789260714372,  2.095903274289385, 2.2618595071429146,
        2.402173502732879, 2.5237190142858297,  2.630929753571457,
       2.7268330278608417, 2.8135880922155954, 2.8927892607143724,
         2.96564727304425,  3.033103256304337, 3.0959032742893844,
        3.154648767857287, 3.2098316767340234, 3.2618595071429146,
       3.3110736128178324,  3.357762781432299, 3.4021735027328797,
       3.4445178457870527, 3.4849795837717283, 3.5237190142858297,
       3.5608767950073115, 3.5965770266157073, 3.6309297535714573,
       3.6640330098757947, 3.6959745056821194, 3.7268330278608417,
        3.756679610828472,  3.785578521428744,  3.813588092215595,
       3.8407614303054807, 3.8671470234508067,  3.892789260714372,
       3.9177288817897304, 3.9420033663892897, 3.9656472730442496,
       3.9886925350037563,  4.011168719591413, 4.0331032563043365,
       4.0545216380691365,   4.07544759935851, 

* In Python, using pandas, NaN is not treated as a level in a categorical type by default. Pandas does not allow NaN to be a category. To include NaN as a level, you need to explicitly handle it by filling them with a placeholder value (like "NaN" or a specific number) before making the data categorical. Use `categorical` and `isna` from pandas.

In [51]:
# Replace NaN with a placeholder value (e.g., 'NaN')
x_filled = [val if not pd.isna(val) else 'NaN' for val in x]

# Convert to categorical
x_factor = pd.Categorical(x_filled)

# Check the unique levels (including 'NaN' as a level)
factor_levels = x_factor.categories
num_levels = len(factor_levels)

print(f"Factor levels (including NaN): {factor_levels}")
print(f"Number of levels: {num_levels}")

Factor levels (including NaN): Index([0.6309297535714574, 1.2618595071429148, 1.6309297535714573,
        1.892789260714372,  2.095903274289385, 2.2618595071429146,
        2.402173502732879, 2.5237190142858297,  2.630929753571457,
       2.7268330278608417, 2.8135880922155954, 2.8927892607143724,
         2.96564727304425,  3.033103256304337, 3.0959032742893844,
        3.154648767857287, 3.2098316767340234, 3.2618595071429146,
       3.3110736128178324,  3.357762781432299, 3.4021735027328797,
       3.4445178457870527, 3.4849795837717283, 3.5237190142858297,
       3.5608767950073115, 3.5965770266157073, 3.6309297535714573,
       3.6640330098757947, 3.6959745056821194, 3.7268330278608417,
        3.756679610828472,  3.785578521428744,  3.813588092215595,
       3.8407614303054807, 3.8671470234508067,  3.892789260714372,
       3.9177288817897304, 3.9420033663892897, 3.9656472730442496,
       3.9886925350037563,  4.011168719591413, 4.0331032563043365,
       4.0545216380691365,   4.

* Cast `x` to integers. Use `where`, `isinfinite` from numpy and `astype` from base python.

In [53]:
x_clean = np.where(np.isfinite(x), x, 0)
x_int = x_clean.astype(int)

print("Cleaned array:", x_clean)
print("Interger array:", x_int)

Cleaned array: [0.         4.19180655 4.17341725 4.15464877 4.13548513 4.11590934
 4.09590327 4.0754476  4.05452164 4.03310326 4.01116872 3.98869254
 3.96564727 3.94200337 3.91772888 3.89278926 3.86714702 3.84076143
 3.81358809 3.78557852 3.75667961 3.72683303 3.69597451 3.66403301
 3.63092975 3.59657703 3.5608768  3.52371901 3.48497958 3.44451785
 3.4021735  3.35776278 3.31107361 3.26185951 3.20983168 3.15464877
 3.09590327 3.03310326 2.96564727 2.89278926 2.81358809 2.72683303
 2.63092975 2.52371901 2.4021735  2.26185951 2.09590327 1.89278926
 1.63092975 1.26185951 0.63092975]
Interger array: [0 4 4 4 4 4 4 4 4 4 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 2 2 2 2 2 2 2 2 2 1 1 1 0]


* Use `x` to create a new vector `y` containing only the real numbers in x. Use `isnan`, `logical_and`, and `reduce` from numpy

In [55]:
y = ~np.isnan(x_int) & np.isfinite(x_int) & (x_int > 0)
print(y)

[False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False]


* Use the left rectangle method to numerically integrate x^2 from 0 to 1 with rectangle width size 1e-6. Use `arrange` and `sum` from numpy

In [57]:
# Define the rectangle width
width = 1e-6

# Create the sequence for the left endpoints (similar to seq in R)
x = np.arange(0, 1, width)

# Compute the sum using the left rectangle method
approximation = np.sum(x ** 2) * width

# Print the result
print(approximation)


0.33333283333349994


* Calculate the average of 100 realizations of standard Bernoullis in one line using the numpy's random.choice function.

In [59]:
avg_bernoulli = np.mean(np.random.choice([0,1], size = 100, p = [.5, .5]))

print(avg_bernoulli)

0.45


* Calculate the average of 500 realizations of Bernoullis with p = 0.9 in one line using the `random.choice` and `mean` functions in numpy.

In [61]:
avg_bernoulli = np.mean(np.random.choice([0,1], size = 500, p = [.1, .9]))

print(avg_bernoulli)

0.896


* Calculate the average of 1000 realizations of Bernoullis with p = 0.9 in one line using `binom` from scipy.stats.

In [157]:
from scipy.stats import binom

avg_bernoulli = binom.rvs(n = 1, p = .9, size = 1000).mean()

print(avg_bernoulli)

0.906


* Let `n = 50`. Create a n x n matrix `R` of exactly 50% entries 0's, 25% 1's 25% 2's. These values should be in random locations.

In [89]:
import pandas as pd

# Set n
n = 50

# Generate the random values with specified proportions
values = np.random.permutation(
    np.concatenate([
        np.full(int(n * n * 0.5), 0),  # 50% 0's
        np.full(int(n * n * 0.25), 1), # 25% 1's
        np.full(int(n * n * 0.25), 2)  # 25% 2's
    ])
)

# Reshape the values into an n x n matrix
R = values.reshape(n, n)

# Convert the matrix into a DataFrame
df = pd.DataFrame(R)

# Print the DataFrame
print(df)

    0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0    0   1   1   0   1   2   0   0   2   1  ...   0   2   1   2   0   1   0   
1    1   2   0   0   0   2   0   1   1   2  ...   2   1   0   1   0   1   0   
2    0   1   2   2   0   2   2   0   1   1  ...   2   2   0   0   0   0   2   
3    0   0   2   0   1   0   2   2   2   2  ...   0   0   1   0   0   1   0   
4    2   1   0   0   1   1   2   2   2   1  ...   1   2   2   0   0   2   0   
5    0   1   0   2   0   2   1   1   2   0  ...   1   0   0   0   0   0   0   
6    1   0   0   0   0   1   0   0   1   2  ...   1   0   1   0   1   0   2   
7    1   1   0   1   1   2   1   1   0   2  ...   0   0   2   0   2   0   0   
8    1   2   1   0   0   2   1   1   0   0  ...   1   1   0   0   2   0   0   
9    0   0   1   0   2   2   2   2   0   2  ...   0   2   0   1   0   1   1   
10   2   0   2   0   1   0   0   2   0   0  ...   0   0   1   0   1   0   1   
11   0   2   1   2   2   0   0   0   1   0  ...   0 

* Randomly punch holes (i.e. `NA`) values in this matrix so that an each entry is missing with probability 30%.

In [91]:
# Convert to float to allow NaN
#df = df.astype(float)

# Randomly punch holes with 30% probability
mask = np.random.choice([True, False], size=df.shape, p=[0.3, 0.7])
df[mask] = np.nan

# View the resulting DataFrame
print(df)

     0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   0.0  1.0  1.0  0.0  NaN  2.0  0.0  NaN  2.0  1.0  ...  0.0  2.0  1.0  2.0   
1   1.0  2.0  0.0  0.0  0.0  NaN  0.0  NaN  1.0  NaN  ...  2.0  1.0  NaN  1.0   
2   0.0  1.0  2.0  2.0  0.0  2.0  2.0  0.0  1.0  NaN  ...  2.0  2.0  0.0  0.0   
3   0.0  0.0  2.0  0.0  1.0  NaN  NaN  2.0  2.0  NaN  ...  0.0  0.0  1.0  0.0   
4   2.0  1.0  0.0  NaN  1.0  1.0  2.0  2.0  NaN  1.0  ...  1.0  2.0  NaN  0.0   
5   0.0  1.0  0.0  NaN  0.0  2.0  1.0  1.0  NaN  0.0  ...  NaN  0.0  NaN  0.0   
6   1.0  0.0  0.0  NaN  0.0  1.0  NaN  NaN  NaN  2.0  ...  NaN  0.0  1.0  NaN   
7   1.0  NaN  0.0  1.0  1.0  2.0  1.0  1.0  0.0  2.0  ...  0.0  0.0  2.0  0.0   
8   1.0  2.0  1.0  0.0  0.0  2.0  1.0  NaN  NaN  0.0  ...  NaN  1.0  NaN  0.0   
9   NaN  0.0  NaN  NaN  2.0  2.0  2.0  NaN  0.0  2.0  ...  NaN  2.0  NaN  1.0   
10  NaN  0.0  NaN  NaN  1.0  0.0  0.0  2.0  0.0  0.0  ...  0.0  NaN  NaN  0.0   
11  0.0  2.0  1.0  2.0  2.0 

In [93]:
import numpy as np
import pandas as pd

# Set matrix dimensions and proportions
n = 50
values = np.random.permutation(
    np.concatenate([
        np.full(int(n * n * 0.5), 0),  # 50% 0's
        np.full(int(n * n * 0.25), 1), # 25% 1's
        np.full(int(n * n * 0.25), 2)  # 25% 2's
    ])
)

# Reshape the matrix
R = values.reshape(n, n)

# Create a mask for punching holes with a 30% probability
random_holes = np.random.choice([True, False], size=(n, n), p=[0.3, 0.7])

# Assign NaN to the corresponding positions
R = R.astype(float)  # Convert to float to support NaN
R[random_holes] = np.nan

# Convert to DataFrame
df = pd.DataFrame(R)


print(df)


     0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   NaN  1.0  NaN  0.0  2.0  0.0  0.0  NaN  0.0  0.0  ...  1.0  2.0  0.0  0.0   
1   0.0  0.0  0.0  0.0  2.0  0.0  0.0  NaN  NaN  0.0  ...  0.0  2.0  0.0  NaN   
2   2.0  1.0  1.0  0.0  NaN  NaN  NaN  0.0  1.0  0.0  ...  1.0  1.0  1.0  0.0   
3   NaN  NaN  2.0  NaN  2.0  0.0  NaN  0.0  NaN  NaN  ...  NaN  2.0  NaN  0.0   
4   NaN  0.0  0.0  NaN  2.0  NaN  1.0  NaN  0.0  1.0  ...  2.0  NaN  2.0  2.0   
5   0.0  2.0  NaN  0.0  NaN  NaN  0.0  2.0  0.0  0.0  ...  NaN  0.0  NaN  NaN   
6   NaN  NaN  0.0  2.0  0.0  0.0  1.0  1.0  NaN  0.0  ...  1.0  NaN  NaN  0.0   
7   0.0  NaN  0.0  NaN  NaN  0.0  NaN  NaN  0.0  0.0  ...  NaN  2.0  2.0  NaN   
8   NaN  2.0  0.0  1.0  NaN  1.0  0.0  0.0  1.0  1.0  ...  1.0  1.0  2.0  1.0   
9   0.0  NaN  NaN  0.0  2.0  NaN  1.0  1.0  2.0  NaN  ...  NaN  0.0  0.0  0.0   
10  NaN  0.0  2.0  0.0  0.0  0.0  1.0  2.0  NaN  NaN  ...  0.0  1.0  NaN  1.0   
11  0.0  0.0  1.0  NaN  2.0 

* Sort the rows in matrix `R` by the largest row sum to lowest. Be careful about the NA's!

In [95]:
#compute row sums, ignoring nan values

row_sum = np.nansum(R, axis = 1)
#print(row_sum)

#get the row indices sorted by largest row sum to smallest

row_sort = np.argsort(-row_sum)
print(row_sort)

[17 15 34 11 24 45 39 25  9 31 44 12  5 42 43 30 29 32  0 49  3 13  8  2
 28 22 48 38 20 23 18 47  6 19 14 26 16 21 40  4 46 27  7 41 10 35 36 37
  1 33]


* Python does not have an apply function. Instead use the nanstd function in numpy to calculate the standard devation of each column. Print them and combine then into a dataframe.

In [97]:
#compute row-wise and column-wise SD
row_sd = np.nanstd(R, axis = 1)
col_sd = np.nanstd(R, axis = 0)

#combine the results into a dictionary
result = {"row_sd": row_sd.tolist(), "col_sd": col_sd.tolist()}

#print the results
print(result["row_sd"])
print(result["col_sd"])

#Count of valid values in col_sd
row_sd_count = sum(~np.isnan(result["row_sd"]))
col_sd_count = sum(~np.isnan(result["col_sd"]))

#print the counts
print("Count of non-Nan values in row_sd:", row_sd_count)
print("Count of non-Nan values in col_sd:", col_sd_count)

[0.9131223741405675, 0.8134892168199607, 0.7870038119348597, 0.8441447440717649, 0.7810249675906653, 0.8660254037844386, 0.7130832029440798, 0.7806247497997998, 0.7810249675906654, 0.8857280869283211, 0.7473912964438374, 0.7528858528207633, 0.8546696378833457, 0.8569568250501305, 0.8261047025600549, 0.8351646544245033, 0.8379429798619952, 0.944013470085026, 0.7870051858976266, 0.8123867916017438, 0.8691737796972567, 0.7556372504853025, 0.7307192465536614, 0.8624393618641034, 0.8392220378474723, 0.8660254037844386, 0.6739081904346824, 0.7848725845546091, 0.8213137116947162, 0.8426193117902646, 0.8446711713768277, 0.9180269263480239, 0.7720238087298051, 0.6110100926607788, 0.8271701918685112, 0.6569540420811757, 0.7259519080762211, 0.6448992647913278, 0.8071991634090854, 0.8559031717046194, 0.8813963377120598, 0.8538789577942649, 0.8632220772029855, 0.8778452283278408, 0.8870956969291443, 0.8714212528966688, 0.8314794192830981, 0.8744417862270764, 0.8400146090767596, 0.8058380730643099]


* combine the results from the previous cell into a dataframe

In [99]:
sd_df = pd.DataFrame({"row_sd": row_sd.tolist(), "col_sd": col_sd.tolist()})
sd_df

row_sd    col_sd
0   0.913122  0.778215
1   0.813489  0.844671
2   0.787004  0.721688
3   0.844145  0.819680
4   0.781025  0.881595
5   0.866025  0.899827
6   0.713083  0.727060
7   0.780625  0.819084
8   0.781025  0.837029
9   0.885728  0.823529
10  0.747391  0.845765
11  0.752886  0.778175
12  0.854670  0.784873
13  0.856957  0.833732
14  0.826105  0.710970
15  0.835165  0.842244
16  0.837943  0.791664
17  0.944013  0.899996
18  0.787005  0.846154
19  0.812387  0.852803
20  0.869174  0.821678
21  0.755637  0.856094
22  0.730719  0.817062
23  0.862439  0.864728
24  0.839222  0.768013
25  0.866025  0.783318
26  0.673908  0.843933
27  0.784873  0.826556
28  0.821314  0.871208
29  0.842619  0.778215
30  0.844671  0.874118
31  0.918027  0.868773
32  0.772024  0.673704
33  0.611010  0.755637
34  0.827170  0.725062
35  0.656954  0.831232
36  0.725952  0.918027
37  0.644899  0.796477
38  0.807199  0.804328
39  0.855903  0.845484
40  0.881396  0.884903
41  0.853879  0.843748
42  0.863222  0.892797
43  0.877845  0.691641
44  0.887096  0.813157
45  0.871421  0.831655
46  0.831479  0.851244
47  0.874442  0.844145
48  0.840015  0.797372
49  0.805838  0.773799

* Use the Pandas apply function to compute a vector whose entries are the count of entries that are 1 or 2 in each column

In [101]:
R = pd.DataFrame(R)  

#Compute the count of 1's and 2's in each column
counts = R.apply(lambda col: ((col == 1) | (col == 2)).sum(), axis=0)

#Print the counts
#print(counts)

Since we just switched between Pandas dataframes and Numpy arrays. Here are some handy ways to check to see if you are working with a Pandas dataframe or a Numpy array

In [103]:
# Check type directly
if type(R) == pd.DataFrame:
    print("R is a Pandas DataFrame")

if type(R) == np.ndarray:
    print("R is a NumPy array")

R is a Pandas DataFrame


In [105]:
# isinstance(object, classinfo): This function checks if an object is an instance of a specified class or subclass.
# function utilizing this function to check
def check_type(R):
    if isinstance(R, pd.DataFrame):
        return "Pandas DataFrame"
    elif isinstance(R, np.ndarray):
        return "NumPy array"
    else:
        return "Unknown type"

# Test the function
print(check_type(R))  # Output: Pandas DataFrame

Pandas DataFrame


* Create a list whose keys are the column number and values are the vector of the columns.

In [107]:
column_dict_from_R = {col: R[col].tolist() for col in R.columns}

* Create a list whose keys are the column number and values are themselves a list with keys: "min" whose value is the minimum of the column, "max" whose value is the maximum of the column, "pct_missing" is the proportion of missingness in the column and "first_NA" whose value is the row number of the first time the NA appears. In R this was accomplished using lappy. In Python we will use dictionary comprehension in tandem with Numpy and Pandas operations.

In [109]:
# Create a dictionary with the required statistics for each column
column_stats = {
    col: {
        "min": R[col].min(),  # Minimum value in the column
        "max": R[col].max(),  # Maximum value in the column
        "pct_missing": R[col].isna().mean(),  # Proportion of missing values
        "first_NA": R[col].isna().idxmax() if R[col].isna().any() else None  # First NA index, None if no NA
    }
    for col in R.columns
}

# Display the dictionary
column_stats


{0: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.38, 'first_NA': 0},
 1: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.3, 'first_NA': 3},
 2: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.28, 'first_NA': 0},
 3: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.36, 'first_NA': 3},
 4: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.26, 'first_NA': 2},
 5: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.32, 'first_NA': 2},
 6: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.38, 'first_NA': 2},
 7: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.36, 'first_NA': 0},
 8: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.28, 'first_NA': 1},
 9: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.32, 'first_NA': 3},
 10: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.22, 'first_NA': 1},
 11: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.4, 'first_NA': 0},
 12: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.38, 'first_NA': 1},
 13: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.38, 'first_NA': 1},
 14: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.26, 'first_NA': 2},
 15: {'

* Set a seed and then create a vector `v` consisting of a sample of 1,000 iid normal realizations with mean -10 and variance 100.

In [167]:
np.random.seed(3)

v = np.random.normal(loc=-10, scale=10, size=1000)
#print(v)

* Repeat this exercise by resetting the seed to ensure you obtain the same results. You can use the random module built in python or random.seed from numpy.

In [169]:
np.random.seed(3)

v = np.random.normal(loc=-10, scale=10, size=1000)
#print(v)

* Find the average of `v` and the standard error of `v`.

In [171]:
mean_v = np.mean(v)

standard_error_v = np.std(v, ddof = 1) / np.sqrt(len(v))  

print(mean_v)
print(standard_error_v)


-9.827156670191656
0.31904424180550645


* Find the 5%ile of `v` and use the `norm` function from scipy.stats to compute what it theoretically should be. Is the estimate about what is expected by theory?

In [173]:
import scipy.stats

std_v = np.std(v, ddof=1) 
fifth_percentile_theoretical = scipy.stats.norm.ppf(0.05, loc=mean_v, scale=std_v)

print(fifth_percentile_theoretical)

-26.422191473803032


* What is the percentile of `v` that corresponds to the value 0? What should it be theoretically? Is the estimate about what is expected by theory?

In [175]:
from scipy.stats import stats

std_v = np.std(v[0], ddof = 1) 
fifth_percentile_theoretical = scipy.stats.norm.ppf(0.05, loc=mean_v, scale=std_v)

print(fifth_percentile_theoretical)

nan


* Create a function `my_reverse` which takes as required input a vector `v` and returns the vector in reverse where the first entry is the last entry, etc. No function calls are allowed inside your function otherwise that would defeat the purpose of the exercise! (Yes, there is a base R function that does this called `rev`). 

In [177]:
def my_reverse(v):
    return v[::-1]

#v = kist(range(10))
#print(my_reverse(v))

 * Built in methods in python to reverse a list.

In [125]:
#reverse using slicing
v = [1, 2, 3, 4, 5]
v_reversed = v[::-1]
print(v_reversed)

#using the .reverse method
v = [1, 2, 3, 4, 5]
v.reverse()
print(v)

[5, 4, 3, 2, 1]
[5, 4, 3, 2, 1]


* Create a function `flip_matrix` which takes as required input a matrix, an argument `dim_to_rev` that returns the matrix with the rows in reverse order or the columns in reverse order depending on the `dim_to_rev` argument. Let the default be the dimension of the matrix that is greater.

In [127]:
def flip_matrix(matrix, dim_to_rev = None):
    if dim_to_rev is None:
        dim_to_rev = 'row' if len(matrix) >= len(matrix[0]) else 'col'
        
    if dim_to_rev[0].lower() == 'r':
        return matrix[::-1]
    else:
        return [row[::-1] for row in matrix]
matrix = [
    [1, 2],
    [3, 4]
]
print(flip_matrix(matrix))
print(flip_matrix(matrix, 'col'))

[[3, 4], [1, 2]]
[[2, 1], [4, 3]]


* Create a list named `my_list` with keys "A", "B", ... where the entries are arrays of size 1, 2 x 2, 3 x 3 x 3, etc. Fill the array with the numbers 1, 2, 3, etc. Make 8 entries according to this sequence.

In [197]:
import numpy as np

my_list = [np.arange(1, i**i + 1).reshape([i] * i) for i in range(1, 4)]

for i, matrix in enumerate(my_list[:8], start=1):
    print(f"Matrix {i}: shape = {matrix.shape}")
    print(matrix, "\n")

Matrix 1: shape = (1,)
[1] 

Matrix 2: shape = (2, 2)
[[1 2]
 [3 4]] 

Matrix 3: shape = (3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 



* Run the following code:

In [199]:
import sys

sizes = {i: sys.getsizeof(value) for i, value in enumerate(my_list, start=1)}

# Print the sizes
for key, size in sizes.items():
    print(f"Matrix {key}: Size: {size} bytes")

Matrix 1: Size: 112 bytes
Matrix 2: Size: 128 bytes
Matrix 3: Size: 144 bytes


* Create vector `v` consisting of all numbers from -100 to 100 and test using the second line of code

In [193]:
import sys

v = list(range(-100, 101))
sizes = {number: sys.getsizeof(number) for number in v}

for number, size in sizes.items():
    print(f"Number: {number}, Size: {size} bytes")

Number: -100, Size: 28 bytes
Number: -99, Size: 28 bytes
Number: -98, Size: 28 bytes
Number: -97, Size: 28 bytes
Number: -96, Size: 28 bytes
Number: -95, Size: 28 bytes
Number: -94, Size: 28 bytes
Number: -93, Size: 28 bytes
Number: -92, Size: 28 bytes
Number: -91, Size: 28 bytes
Number: -90, Size: 28 bytes
Number: -89, Size: 28 bytes
Number: -88, Size: 28 bytes
Number: -87, Size: 28 bytes
Number: -86, Size: 28 bytes
Number: -85, Size: 28 bytes
Number: -84, Size: 28 bytes
Number: -83, Size: 28 bytes
Number: -82, Size: 28 bytes
Number: -81, Size: 28 bytes
Number: -80, Size: 28 bytes
Number: -79, Size: 28 bytes
Number: -78, Size: 28 bytes
Number: -77, Size: 28 bytes
Number: -76, Size: 28 bytes
Number: -75, Size: 28 bytes
Number: -74, Size: 28 bytes
Number: -73, Size: 28 bytes
Number: -72, Size: 28 bytes
Number: -71, Size: 28 bytes
Number: -70, Size: 28 bytes
Number: -69, Size: 28 bytes
Number: -68, Size: 28 bytes
Number: -67, Size: 28 bytes
Number: -66, Size: 28 bytes
Number: -65, Size: 

* Test the `my_reverse` function using the following code:

In [135]:
# Test the function
v = list(range(1, 11))
v_reversed = my_reverse(v)
print(v)
print(v_reversed)
type(v_reversed)

assert my_reverse(v) == v[::-1], "my_reverse failed for numerical vector"

 # Test with character vector
v_char = ["A", "B", "C"]
assert my_reverse(v_char) == v_char[::-1], "my_reverse failed for character vector"

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


## A little about strings

* Use the `re.split` function by importing the re module and `random` from the random module to put the sentences in the string `lorem` below in random order. You will also need to manipulate the output of `re.split` which is a list. You may need to learn basic concepts of regular expressions.

In [137]:
import re
import random

lorem = """Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Morbi posuere varius volutpat. Morbi faucibus ligula id massa ultricies viverra.
Donec vehicula sagittis nisi non semper. Donec at tempor erat.
Integer dapibus mi lectus, eu posuere arcu ultricies in.
Cras suscipit id nibh lacinia elementum. Curabitur est augue, congue eget quam in, scelerisque semper magna.
Aenean nulla ante, iaculis sed vehicula ac, finibus vel arcu. Mauris at sodales augue."""

sentences = re.split(r'(?<=[.!?])\s+', lorem)
sentences = [s.strip() for s in sentences if s.strip()]
random.shuffle(sentences)
for sentence in sentences:
    print(sentence)



Morbi posuere varius volutpat.
Aenean nulla ante, iaculis sed vehicula ac, finibus vel arcu.
Mauris at sodales augue.
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Morbi faucibus ligula id massa ultricies viverra.
Donec at tempor erat.
Cras suscipit id nibh lacinia elementum.
Curabitur est augue, congue eget quam in, scelerisque semper magna.
Donec vehicula sagittis nisi non semper.
Integer dapibus mi lectus, eu posuere arcu ultricies in.


* You have a set of names divided by gender (M / F) and generation (Boomer / GenX / Millenial):

M / Boomer      "Theodore, Bernard, Gene, Herbert, Ray, Tom, Lee, Alfred, Leroy, Eddie"

M / GenX        "Marc, Jamie, Greg, Darryl, Tim, Dean, Jon, Chris, Troy, Jeff"

M / Millennial  "Zachary, Dylan, Christian, Wesley, Seth, Austin, Gabriel, Evan, Casey, Luis"

F / Boomer      "Gloria, Joan, Dorothy, Shirley, Betty, Dianne, Kay, Marjorie, Lorraine, Mildred"

F / GenX        "Tracy, Dawn, Tina, Tammy, Melinda, Tamara, Tracey, Colleen, Sherri, Heidi"

F / Millennial  "Samantha, Alexis, Brittany, Lauren, Taylor, Bethany, Latoya, Candice, Brittney, Cheyenne"

Create python dictionary to store this data.


In [139]:
names = {
    "M": {
        "Boomer": ["Theodore", "Bernard", "Gene", "Herbert", "Ray", "Tom", "Lee", "Alfred", "Leroy", "Eddie"],
        "GenX": ["Marc", "Jamie", "Greg", "Darryl", "Tim", "Dean", "Jon", "Chris", "Troy", "Jeff"],
        "Millennial": ["Zachary", "Dylan", "Christian", "Wesley", "Seth", "Austin", "Gabriel", "Evan", "Casey", "Luis"]
    },
    "F": {
        "Boomer": ["Gloria", "Joan", "Dorothy", "Shirley", "Betty", "Dianne", "Kay", "Marjorie", "Lorraine", "Mildred"],
        "GenX": ["Tracy", "Dawn", "Tina", "Tammy", "Melinda", "Tamara", "Tracey", "Colleen", "Sherri", "Heidi"],
        "Millennial": ["Samantha", "Alexis", "Brittany", "Lauren", "Taylor", "Bethany", "Latoya", "Candice", "Brittney", "Cheyenne"]
    }
}

print("Millennial (M):", names["M"]["Millennial"])
print("Boomer (F):", names["F"]["Boomer"])

Millennial (M): ['Zachary', 'Dylan', 'Christian', 'Wesley', 'Seth', 'Austin', 'Gabriel', 'Evan', 'Casey', 'Luis']
Boomer (F): ['Gloria', 'Joan', 'Dorothy', 'Shirley', 'Betty', 'Dianne', 'Kay', 'Marjorie', 'Lorraine', 'Mildred']


* Now cleanup the namespace by deleting all stored objects and functions:

In [141]:
for name in list(globals().keys()):
    if name not in ('__builtins__', '__doc__', '__name__', '__package__'):
        del globals()[name]